### ISSUE TITLE
How can I select the discourse version to install in docker ?

### ISSUE THREAD

**Issue by harobed** [discourse/discourse_docker#165]
Hi,

I've installed docer discourse with success (in EN, there are issue with French).

I see it's unstable version installed : v1.3.0.beta9 +214 
How can I install last stable version : v1.2.4 

Suggest : append a section in README about version installation selection

Best regards,
Stéphane

**Comment by jamielinux** [comment]
Look in `standalone.yml` or `web_only.yml`:
```yaml
params:
  # Which Git revision should this container use? (default: tests-passed)
  version: tests-passed
```
