### ISSUE TITLE
Can't install plugins

### ISSUE THREAD

**Issue by machisuji** [discourse/discourse_docker#218]
When looking up how to install plugins in your docker-based discourse instance you find [this](https://meta.discourse.org/t/install-a-plugin/19157).

I've tried this and it doesn't seem to work. I've based my container yml on the given standalone sample which already includes a section for the docker_manager plugin. But not even this plugin is installed. Are the instructions out of date by any chance?

**Comment by lidel** [comment]
Instructions are fine, I updated my instance last week and it has https://github.com/kasperpeulen/discourse-mathjax installed that way.  
Are you sure you are editing `/var/discourse/containers/app.yml` 
and rebuilding via `/var/discourse/launcher rebuild app` ? ("app" being the name of config file)

**Comment by machisuji** [comment]
Mh, I'm pretty sure.

```
~ cat containers/app.yml | grep -B20 docker_manager
  ## The CDN address for this Discourse instance (configured to pull)
  #DISCOURSE_CDN_URL: //discourse-cdn.example.com

## These containers are stateless, all data is stored in /shared
volumes:
  - volume:
      host: /data/discourse/shared/standalone
      guest: /shared
  - volume:
      host: /data/discourse/shared/standalone/log/var-log
      guest: /var/log

## The docker manager plugin allows you to one-click upgrade Discourse
## http://discourse.example.com/admin/docker
hooks:
  after_code:
    - exec:
        cd: $home/plugins
        cmd:
          - mkdir -p plugins
          - git clone https://github.com/discourse/docker_manager.git
```

So it's in my app.yml. Then I do `./launcher rebuild app` and the result does not include the plugins.
I'm sure I'm editing the right file and building the right containers. Other things I've included like postgres hooks (adding users, altering tables etc.) work just fine.
