### ISSUE TITLE
web_only sample fails to bootstrap on db:migrate

### ISSUE THREAD

**Issue by BrianHicks** [discourse/discourse_docker#3]
the `rake db:migrate` step of bootstrapping the `web_only` container (modified slightly from sample) fails with the following error:

```
I, [2014-01-13T00:42:56.743763 #38]  INFO -- : > cd /var/www/discourse && sudo -E -u discourse bundle exec rake db:migrate
rake aborted!
YAML syntax error occurred while parsing /var/www/discourse/config/database.yml. Please note that YAML must be consistently indented using spaces. Tabs are not allowed. Error: (<unknown>): found character that cannot start any token while scanning for the next token at line 45 column 13
/var/www/discourse/vendor/bundle/ruby/2.0.0/gems/railties-4.0.2/lib/rails/application/configuration.rb:113:in `rescue in database_configuration'
/var/www/discourse/vendor/bundle/ruby/2.0.0/gems/railties-4.0.2/lib/rails/application/configuration.rb:103:in `database_configuration'
/var/www/discourse/vendor/bundle/ruby/2.0.0/gems/activerecord-4.0.2/lib/active_record/railtie.rb:175:in `block (2 levels) in <class:Railtie>'
/var/www/discourse/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/lazy_load_hooks.rb:38:in `instance_eval'
/var/www/discourse/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/lazy_load_hooks.rb:38:in `execute_hook'
/var/www/discourse/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/lazy_load_hooks.rb:28:in `block in on_load'
/var/www/discourse/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/lazy_load_hooks.rb:27:in `each'
/var/www/discourse/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/lazy_load_hooks.rb:27:in `on_load'
/var/www/discourse/vendor/bundle/ruby/2.0.0/gems/activerecord-4.0.2/lib/active_record/railtie.rb:174:in `block in <class:Railtie>'
/var/www/discourse/vendor/bundle/ruby/2.0.0/gems/railties-4.0.2/lib/rails/initializable.rb:30:in `instance_exec'
/var/www/discourse/vendor/bundle/ruby/2.0.0/gems/railties-4.0.2/lib/rails/initializable.rb:30:in `run'
/var/www/discourse/vendor/bundle/ruby/2.0.0/gems/railties-4.0.2/lib/rails/initializable.rb:55:in `block in run_initializers'
/var/www/discourse/vendor/bundle/ruby/2.0.0/gems/railties-4.0.2/lib/rails/initializable.rb:54:in `run_initializers'
/var/www/discourse/vendor/bundle/ruby/2.0.0/gems/railties-4.0.2/lib/rails/application.rb:215:in `initialize!'
/var/www/discourse/vendor/bundle/ruby/2.0.0/gems/railties-4.0.2/lib/rails/railtie/configurable.rb:30:in `method_missing'
/var/www/discourse/config/environment.rb:5:in `<top (required)>'
/var/www/discourse/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `require'
/var/www/discourse/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `block in require'
/var/www/discourse/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:214:in `load_dependency'
/var/www/discourse/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `require'
/var/www/discourse/vendor/bundle/ruby/2.0.0/gems/railties-4.0.2/lib/rails/application.rb:189:in `require_environment!'
/var/www/discourse/vendor/bundle/ruby/2.0.0/gems/railties-4.0.2/lib/rails/application.rb:250:in `block in run_tasks_blocks'
Tasks: TOP => db:migrate => environment
(See full trace by running task with --trace)
I, [2014-01-13T00:43:03.653073 #38]  INFO -- :
/pups/lib/pups/exec_command.rb:85:in `spawn': cd /var/www/discourse && sudo -E -u discourse bundle exec rake db:migrate failed with return #<Process::Status: pid 130 exit 1> (RuntimeError)
        from /pups/lib/pups/exec_command.rb:55:in `block in run'
        from /pups/lib/pups/exec_command.rb:53:in `each'
        from /pups/lib/pups/exec_command.rb:53:in `run'
        from /pups/lib/pups/command.rb:6:in `run'
        from /pups/lib/pups/config.rb:82:in `block (2 levels) in run_commands'
        from /pups/lib/pups/config.rb:73:in `each'
        from /pups/lib/pups/config.rb:73:in `block in run_commands'
        from /pups/lib/pups/config.rb:72:in `each'
        from /pups/lib/pups/config.rb:72:in `run_commands'
        from /pups/lib/pups/config.rb:68:in `run'
        from /pups/lib/pups/cli.rb:31:in `run'
        from /pups/bin/pups:8:in `<main>'
0c296d25ce2ebb1afc4d0efcbcce61b0c9aa07a881191048b5a5c292ffa3915a
FAILED TO BOOTSTRAP
```
Here's the config:

```
# IMPORTANT: SET A SECRET PASSWORD in Postgres for the Discourse User
# SOME_SECRET in this template

templates:
  - "templates/sshd.template.yml"
  - "templates/web.template.yml"

expose:
  - "80:80"
  - "2222:22"

params:

# your ssh key can go here, or you can use ssh-import-id
  ssh_key: ""
  version: "v0.9.8"

# developer emails allow you to fast track account creation on the site
env:
  # add emails here
  DISCOURSE_DEVELOPER_EMAILS: 'NOPE@NOPE.com'
  DISCOURSE_DB_SOCKET: ''
  DISCOURSE_DB_PASSWORD: 'NOPE'
  DISCOURSE_DB_HOST: 'localhost'
  DISCOURSE_HOSTNAME: 'forums.stlpython.com'
  DISCOURSE_REDIS_HOST: 'localhost'
  # don't forget to set mail
  DISCOURSE_SMTP_ADDRESS: smtp.mandrillapp.com
  DISCOURSE_SMTP_PORT: 587
  DISCOURSE_SMTP_USER_NAME: NOPE@NOPE.com
  DISCOURSE_SMTP_PASSWORD: 'NOPE'

volumes:
  - volume:
        host: /var/docker/shared
        guest: /shared

# you may use the docker manager to upgrade and monitor your docker image
# UI will be visible at http://yoursite.com/admin/docker
hooks:
# you may import your key using launchpad if needed
#after_sshd:
#    - exec: ssh-import-id some-user
  after_code:
    - exec:
        cd: $home/plugins
        cmd:
          - mkdir -p plugins
          - git clone https://github.com/discourse/docker_manager.git
```

Is this something in one of my configs or something upstream? I've tried Discourse HEAD, v0.9.8.1 and v0.9.8 (and a few other hashes behind HEAD). They all fail with the same error.
