### ISSUE TITLE
Error when trying to launch

### ISSUE THREAD

**Issue by envygeeks** [discourse/discourse_docker#367]
```
ubuntu@ip-10-0-0-66:/opt/discourse$ sudo ./launcher bootstrap web

rm: cannot remove 'cids/web_bootstrap.cid': No such file or directory
** FAILED TO BOOTSTRAP ** please scroll up and look for earlier error \
  messages, there may be more than one
```

Contents of `web.yml`

```yml
templates:
  - "templates/web.ratelimited.template.yml"
  - "templates/web.template.yml"
expose:
  - "80:80"
links:
  - link:
      name: data
      alias: data
env:
  LANG: en_US.UTF-8
  DISCOURSE_SMTP_PORT: "587"
  DISCOURSE_REDIS_HOST: "<hidden>"
  DISCOURSE_SMTP_ADDRESS: "smtp.gallifrey.envygeeks.io"
  DISCOURSE_DEVELOPER_EMAILS: "<hidden>"
  DISCOURSE_DB_PASSWORD: "<hidden>"
  DISCOURSE_DB_USERNAME: "discourse"
  DISCOURSE_SMTP_USER_NAME: "<hidden>"
  DISCOURSE_SMTP_PASSWORD: "<hidden>"
  DISCOURSE_DB_HOST: "<hidden>"
  DISCOURSE_REDIS_PORT: "11211"
  DISCOURSE_HOSTNAME: "<removed>"
# --
# This isn't very volatile, we should probably
# Store this data on an EFS, this way the servers can
# be volatile with static data.
# --
volumes:
  - volume:
      host: /opt/discourse/shared/web-only
      guest: /shared
  - volume:
      host: /opt/discourse/shared/web-only/log/var-log
      guest: /var/log
hooks:
  after_code:
    - exec:
        cd: $home/plugins
        cmd:
          - git clone https://github.com/discourse/docker_manager.git
```

Seems to originate here:

https://github.com/discourse/discourse_docker/blob/02d9a654664b3c7fdb518780c6a61c21e208d169/launcher#L589
