### ISSUE TITLE
Unable to connect to postgresql server for db:migrate

### ISSUE THREAD

**Issue by tristil** [discourse/discourse_docker#58]
Getting this error, **unless** I supply `PGHOST`, `PGPASSWORD`, and `DISCOURSE_DB_PORT` in the env hash for `web_only.yml`:

```
psql: could not connect to server: Connection timed out
   Is the server running on host "172.17.42.1" and accepting
  TCP/IP connections on port 5432?
```

This is my config before adding the env variables:

```
# IMPORTANT: SET A SECRET PASSWORD in Postgres for the Discourse User
# SOME_SECRET in this template

templates:
  - "templates/sshd.template.yml"
  - "templates/web.template.yml"

expose:
  - "8081:80"
  - "2222:22"

params:
  version: HEAD

# developer emails allow you to fast track account creation on the site
env:
  # add emails here
  DISCOURSE_DEVELOPER_EMAILS: email@example.com
  DISCOURSE_DB_SOCKET: ''
  DISCOURSE_DB_HOST: 172.17.42.1
  DISCOURSE_DB_PASSWORD: 'SECRET'
  DISCOURSE_REDIS_HOST: 172.17.42.1 
  DISCOURSE_HOSTNAME: forum.berkshirestech.org
  DISCOURSE_SMTP_ADDRESS: smtp.mandrillapp.com
  DISCOURSE_SMTP_PORT: 587
  DISCOURSE_SMTP_USER_NAME: email@example.com
  DISCOURSE_SMTP_PASSWORD: 'SECRET'

volumes:
  - volume:
        host: /var/docker/discourse/shared
        guest: /shared

# you may use the docker manager to upgrade and monitor your docker image
# UI will be visible at http://yoursite.com/admin/docker
hooks:
  after_code:
    - file:
        path: /var/www/discourse/config/multisite.yml
        contents: |
         secondsite:
           adapter: postgresql
           database: b_discourse
           pool: 25
           timeout: 5000
           db_id: 2
           host_names:
             - forum.stupididea.com
             - stupididea_forum.local
    - exec:
        cd: /var/www/discourse/plugins
        cmd:
          - mkdir -p plugins
          - git clone https://github.com/discourse/docker_manager.git
  after_web:
    - exec: cd /var/www/discourse && sudo -E -u discourse bundle exec rake multisite:migrate
```

The config that ended up working for me was the below, which doesn't seem remotely correct. The key changes are PGHOST, PGPASSWORD and DISCOURSE_DB_PORT:

```
env:
  # add emails here
  PGHOST: 172.17.42.1
  PGPASSWORD: SECRET
  DISCOURSE_DEVELOPER_EMAILS: 'email@example.com'
  DISCOURSE_DB_SOCKET: ''
  DISCOURSE_DB_PORT: 5432
  DISCOURSE_DB_PASSWORD: SECRET
  DISCOURSE_DB_HOST: 172.17.42.1
  DISCOURSE_HOSTNAME: berkshirestech_forum.local
  DISCOURSE_REDIS_HOST: 172.17.42.1
  DISCOURSE_SMTP_ADDRESS: smtp.mandrillapp.com
  DISCOURSE_SMTP_PORT: 587
  DISCOURSE_SMTP_USER_NAME: email@example.com
  DISCOURSE_SMTP_PASSWORD: SECRET
```

Only with the combination of all three would anything work. The container seemed to be acting as if the values in config/discourse.conf weren't set for the purposes of rake db:migrate, even though they were:

```
smtp_user_name=email@example.com
db_host=172.17.42.1
developer_emails=email@example.com
smtp_port=587
smtp_password=SECRET
smtp_address=smtp.mandrillapp.com
hostname=berkshirestech_forum.local
db_port=5432
db_socket=
redis_host=172.17.42.1
db_password=SECRET
```
